# ------- Real-time using HAND -------------
[database]
username = admin
# -- if password = 'xxx', python will pull from 'DB_PASSWORD' envionment variable
host = postgis
port = 5432
dbname = 01_PAR_realtime_hand

# -----------------------
; [flow_from_nwm]
; # -- for step 1A
; # For grabbing flow directly from NWM s3 bucket 'noaa-nwm-pds'
; texas_faeture_id_list = /fast_realtime/inputs/texas_feature_ids.csv
; force = true

# -----------------------
; [download]
; # -- for step 1B
; # For grabbing flows from KISTERs
; url = https://knatempstorage.s3.us-west-1.amazonaws.com/nwm_txdot_output/short_range/valid_comids_texas_streamflow.nc
; download_dir = /tmp
; force = true

[bridge_warnings]
enabled = true
# -----------------------
[sql]
# -- for step 2
sql_file_path = /fast_realtime/sql/roadflood_create_dynamic_tables_wf.sql
workflow_id = nwm_sr_02


[local_results]
publish_live = False
publish_historic = False
output_folder = /fast_realtime/output/nwm2/01_PAR
output_folder_historic = /fast_realtime/output/nwm_hist/01_PAR


# -----------------------
[write_to_s3]
; # -- for step 4: this is a full config with all the outputs
# ENV vars: FAST_S3_ACCESS_KEY_ID and FAST_S3_SECRET_ACCESS_KEY
publish_live = true
publish_bucket = knatempstorage
publish_sub_folder = fast_realtime/nwm2/01-PAR
publish_historic = False
publish_historic_bucket = knatempstorage
publish_historic_sub_folder = fast_historic/nwm2/01-PAR

# Enable or disable product outputs
publish_roads = true
publish_bridges = true
publish_inundation = true

# Enable esrijson output
publish_esri_json = false
