# ------- Real-time using HAND -------------
[database]
username = admin
# -- if password = 'xxx', python will pull from 'DB_PASSWORD' envionment variable
host = postgis
port = 5432
dbname = 07_SJT_realtime_hand

# -----------------------
; [flow_from_nwm]
; # -- for step 1A
; # For grabbing flow directly from NWM s3 bucket 'noaa-nwm-pds'
; texas_faeture_id_list = /fast_realtime/inputs/texas_feature_ids.csv
; force = true

# -----------------------
[download]
# -- for step 1B
# For grabbing flows from KISTERs DA
url = https://knatempstorage.s3.us-west-1.amazonaws.com/nwm_txdot_output/short_range_da_kf/valid_comids_texas_streamflow.nc
download_dir = /tmp
; force = true


[bridge_warnings]
enabled = true
# -----------------------
[sql]
# -- for step 2
sql_file_path = /fast_realtime/sql/roadflood_create_dynamic_tables_wf_now.sql
workflow_id = da_sr_nc

[local_results]
publish_live = False
publish_historic = False
output_folder = /fast_realtime/output/07_SJT
# -----------------------
[write_to_s3]
; # -- for step 4
publish_live = true
publish_bucket = knatempstorage
publish_sub_folder = fast_realtime/da_nc/07-SJT
publish_historic = true
publish_historic_bucket = knatempstorage
publish_historic_sub_folder = fast_historic/da_nc/07-SJT

# Enable or disable product outputs
publish_roads = true
publish_bridges = true
publish_inundation = true

# Enable esrijson output
publish_esri_json = false