# ------- Real-time using HAND -------------
[database]
username = admin
# -- if password = null, python will pull from 'DB_PASSWORD' envionment variable
host = postgis
port = 5432
dbname = TXFull

; # -----------------------
; [flow_from_nwm]
; # -- for step 1A
; # For grabbing flow directly from NWM s3 bucket 'noaa-nwm-pds'
; texas_faeture_id_list = /fast_realtime/inputs/texas_feature_ids.csv

; # -----------------------
; [download]
; # -- for step 1B
; # For grabbing flows from KISTERs
; url = https://knatempstorage.s3.us-west-1.amazonaws.com/nwm_txdot_output/short_range/valid_comids_texas_streamflow.nc
; download_dir = /tmp

# -----------------------
; [sql]
; # -- for step 2
; sql_file_path = /fast_realtime/sql/roadflood_create_dynamic_tables_big.sql

[bridge_warnings]
enabled = false

; [local_results]
; output_folder = /fast_realtime/output/da/TXFull
; output_folder_historic = /fast_realtime/output/da_hist/TXFull

; [write_to_s3]
; ; # -- for step 4
; ; # -- will ultimaetly need AWS keys are pulled from the env vars
; publish_bucket = knatempstorage
; publish_sub_folder = fast_realtime/nwm/01-PAR

[merged_view]
sql_file_path = /fast_realtime/sql/create_merged_materialized_view.sql
workflow_id = da_sr_nc

[merged_view.local_output]
publish_live = False
publish_historic = False
output_folder = /fast_realtime/output/da_nc/TXFull
output_folder_historic = /fast_realtime/output/da_nc_hist/TXFull

[merged_view.s3_output]
publish_live = true
publish_bucket = knatempstorage
publish_sub_folder = fast_realtime/da_nc/TXFull
publish_historic = False
publish_historic_bucket = knatempstorage
publish_historic_sub_folder = fast_historic/da_nc/TXFull

# Enable or disable product outputs
publish_roads = true
publish_bridges = true
publish_inundation = true

# Enable esrijson output
publish_esri_json = true


