# ------- Real-time using HAND -------------
[database]
username = admin
# -- if password = null, python will pull from 'DB_PASSWORD' envionment variable
host = postgis
port = 5432
dbname = TXFull

; # -----------------------
; [flow_from_nwm]
; # -- for step 1A
; # For grabbing flow directly from NWM s3 bucket 'noaa-nwm-pds'
; texas_faeture_id_list = /fast_realtime/inputs/texas_feature_ids.csv
; workflow_id = nwm_sr

; # -----------------------
[download]
# -- for step 1B
# For grabbing flows from KISTERs
url = https://knatempstorage.s3.us-west-1.amazonaws.com/nwm_txdot_output/short_range_da_kf/streamflow_kf_sr.nc
download_dir = /tmp
workflow_id = nwm_sr
parameter = streamflow_nwm
force = true
exclude_column_indexes = [18]

# -----------------------
; [sql]
; # -- for step 2
; sql_file_path = /fast_realtime/sql/roadflood_create_dynamic_tables_big.sql

[bridge_warnings]
enabled = false

; [local_results]
; output_folder = /fast_realtime/output/nwm/TXFull
; output_folder_historic = /fast_realtime/output/nwm_hist/TXFull

; [write_to_s3]
; ; # -- for step 4
; ; # -- will ultimaetly need AWS keys are pulled from the env vars
; publish_bucket = knatempstorage
; publish_sub_folder = fast_realtime/nwm/01-PAR

; [merged_view]
; sql_file_path = /fast_realtime/sql/create_merged_materialized_view.sql
; workflow_id = nwm_sr

; [merged_view.local_output]
; publish_live = False
; publish_historic = False
; output_folder = /fast_realtime/output/nwm/TXFull
; output_folder_historic = /fast_realtime/output/nwm_hist/TXFull

; [merged_view.s3_output]
; publish_live = true
; publish_bucket = knatempstorage
; publish_sub_folder = fast_realtime/nwm/TXFull
; publish_historic = true
; publish_historic_bucket = knatempstorage
; publish_historic_sub_folder = fast_historic/nwm/TXFull

; # Enable or disable product outputs
; publish_roads = true
; publish_bridges = true
; publish_inundation = true

; # Enable esrijson output
; publish_esri_json = false
